### ISSUE TITLE
is anyone using this repository?

### ISSUE THREAD

**Issue by iantaylor-NOAA** [pfmc-assessments/nwfscMapping#1]
@chantelwetzel-noaa, you made the most recent code commit in 2018. 
Do you still use this repository?
If we wanted to do more mapping in the future, would it be better to start from this repo or a clean slate?

**Comment by allanhicks** [comment]
Hi everyone,
I started this repository as a place to store some functions, but more
importantly some data that could be used to plot bathymetry and boundaries.
I’m not sure if it was useful, and is probably outdated by now. Curt has
likely updated the bathmetry. There may have been some stitching together
of the coastline down to Mexico for use in PBSmapping.  Do with it as you
wish.

Allan

**Comment by chantelwetzel-noaa** [comment]
I have not used this repo in a few years, however, I have not done much mapping work in that time. I don't think this repo needs to be moved to the new organization and have everything saved locally just in case I want to play with it in the future.

**Comment by iantaylor-NOAA** [comment]
Thanks for the input @allanhicks and @chantelwetzel-noaa.
I will go ahead and archive instead of delete. We can also unarchive or delete later.
